/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BenmoRegistryInterface extends Interface {
    getFunction(nameOrSignature: "registerHandle" | "resolveHandle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HandleRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'registerHandle', values: [string, string]): string;
encodeFunctionData(functionFragment: 'resolveHandle', values: [string]): string;

    decodeFunctionResult(functionFragment: 'registerHandle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveHandle', data: BytesLike): Result;
  }

  
    export namespace HandleRegisteredEvent {
      export type InputTuple = [handleHash: BytesLike, owner: AddressLike];
      export type OutputTuple = [handleHash: string, owner: string];
      export interface OutputObject {handleHash: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BenmoRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): BenmoRegistry;
    waitForDeployment(): Promise<this>;

    interface: BenmoRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    registerHandle: TypedContractMethod<
      [handle: string, unlinkAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    resolveHandle: TypedContractMethod<
      [handle: string, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'registerHandle'): TypedContractMethod<
      [handle: string, unlinkAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveHandle'): TypedContractMethod<
      [handle: string, ],
      [string],
      'view'
    >;

    getEvent(key: 'HandleRegistered'): TypedContractEvent<HandleRegisteredEvent.InputTuple, HandleRegisteredEvent.OutputTuple, HandleRegisteredEvent.OutputObject>;

    filters: {
      
      'HandleRegistered(bytes32,address)': TypedContractEvent<HandleRegisteredEvent.InputTuple, HandleRegisteredEvent.OutputTuple, HandleRegisteredEvent.OutputObject>;
      HandleRegistered: TypedContractEvent<HandleRegisteredEvent.InputTuple, HandleRegisteredEvent.OutputTuple, HandleRegisteredEvent.OutputObject>;
    
    };
  }