/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BenmoRegistry } from './BenmoRegistry.js';
export * as factories from './factories/index.js';
export { BenmoRegistry__factory } from './factories/BenmoRegistry__factory.js';