// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUnlinkPool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUnlinkPool";
  readonly sourceName: "contracts/IUnlinkPool.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"deposit","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IUnlinkPool.sol";
  readonly buildInfoId: "solc-0_8_28-46564788cbb77ef48589926ed66dc05f3e94b41d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUnlinkPool"]: IUnlinkPool$Type;
    ["contracts/IUnlinkPool.sol:IUnlinkPool"]: IUnlinkPool$Type;
  }
}