/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface Web3VenmoShieldInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "owner" | "shieldAndPay" | "totalShielded" | "transferOwnership" | "unlinkPool" | "unshieldAndPay" | "userBalances"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "OwnerTransferred" | "SocialPayment" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'shieldAndPay', values: [AddressLike, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'totalShielded', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unlinkPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'unshieldAndPay', values: [AddressLike, AddressLike, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'userBalances', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shieldAndPay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalShielded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlinkPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unshieldAndPay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBalances', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, token: string, amount: bigint];
      export interface OutputObject {user: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SocialPaymentEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, memo: string];
      export type OutputTuple = [sender: string, receiver: string, memo: string];
      export interface OutputObject {sender: string, receiver: string, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, token: string, recipient: string, amount: bigint];
      export interface OutputObject {user: string, token: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Web3VenmoShield extends BaseContract {
    
    connect(runner?: ContractRunner | null): Web3VenmoShield;
    waitForDeployment(): Promise<this>;

    interface: Web3VenmoShieldInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [token: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    shieldAndPay: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalShielded: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unlinkPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unshieldAndPay: TypedContractMethod<
      [user: AddressLike, token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    userBalances: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [token: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'shieldAndPay'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalShielded'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlinkPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unshieldAndPay'): TypedContractMethod<
      [user: AddressLike, token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBalances'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'OwnerTransferred'): TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
getEvent(key: 'SocialPayment'): TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(address,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'OwnerTransferred(address,address)': TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
      OwnerTransferred: TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
    

      'SocialPayment(address,address,string)': TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;
      SocialPayment: TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;
    

      'Withdrawn(address,address,address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }