/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'IUnlinkPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUnlinkPool__factory>
getContractFactory(name: 'Web3VenmoShield', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Web3VenmoShield__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockUnlinkPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUnlinkPool__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'IUnlinkPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUnlinkPool>
getContractAt(name: 'Web3VenmoShield', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Web3VenmoShield>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockUnlinkPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUnlinkPool>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IUnlinkPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUnlinkPool>
deployContract(name: 'Web3VenmoShield', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Web3VenmoShield>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockUnlinkPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUnlinkPool>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IUnlinkPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUnlinkPool>
deployContract(name: 'Web3VenmoShield', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Web3VenmoShield>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockUnlinkPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUnlinkPool>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  