/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface Web3VenmoShieldInterface extends Interface {
    getFunction(nameOrSignature: "shieldAndPay" | "unlinkPool"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SocialPayment"): EventFragment;

    encodeFunctionData(functionFragment: 'shieldAndPay', values: [AddressLike, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'unlinkPool', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'shieldAndPay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlinkPool', data: BytesLike): Result;
  }

  
    export namespace SocialPaymentEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, memo: string];
      export type OutputTuple = [sender: string, receiver: string, memo: string];
      export interface OutputObject {sender: string, receiver: string, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Web3VenmoShield extends BaseContract {
    
    connect(runner?: ContractRunner | null): Web3VenmoShield;
    waitForDeployment(): Promise<this>;

    interface: Web3VenmoShieldInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    shieldAndPay: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    unlinkPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'shieldAndPay'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, receiver: AddressLike, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlinkPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'SocialPayment'): TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;

    filters: {
      
      'SocialPayment(address,address,string)': TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;
      SocialPayment: TypedContractEvent<SocialPaymentEvent.InputTuple, SocialPaymentEvent.OutputTuple, SocialPaymentEvent.OutputObject>;
    
    };
  }