/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockUnlinkPool, MockUnlinkPoolInterface } from "../../mocks/MockUnlinkPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "shieldedBalances",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061026b8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c806347e7ef24146100435780639508ee7314610058578063f7888aec14610091575b5f5ffd5b610056610051366004610197565b6100a4565b005b61007f6100663660046101bf565b5f60208181529281526040808220909352908152205481565b60405190815260200160405180910390f35b61007f61009f3660046101bf565b610152565b6040516323b872dd60e01b8152336004820152306024820152604481018290526001600160a01b038316906323b872dd906064016020604051808303815f875af11580156100f4573d5f5f3e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061011891906101f0565b506001600160a01b0382165f9081526020818152604080832033845290915281208054839290610149908490610216565b90915550505050565b6001600160a01b038083165f90815260208181526040808320938516835292905220545b92915050565b80356001600160a01b0381168114610192575f5ffd5b919050565b5f5f604083850312156101a8575f5ffd5b6101b18361017c565b946020939093013593505050565b5f5f604083850312156101d0575f5ffd5b6101d98361017c565b91506101e76020840161017c565b90509250929050565b5f60208284031215610200575f5ffd5b8151801515811461020f575f5ffd5b9392505050565b8082018082111561017657634e487b7160e01b5f52601160045260245ffdfea264697066735822122033d651aeaa29f85f23ba571107664a053977c2b6c5af3db6a7bb18e8a77829d664736f6c634300081c0033";

  
      type MockUnlinkPoolConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockUnlinkPoolConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockUnlinkPool__factory extends ContractFactory {
    
      constructor(...args: MockUnlinkPoolConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockUnlinkPool & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockUnlinkPool__factory {
      return super.connect(runner) as MockUnlinkPool__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockUnlinkPoolInterface {
      return new Interface(_abi) as MockUnlinkPoolInterface;
    }
    
    override attach(address: string | Addressable): MockUnlinkPool {
      return super.attach(address) as MockUnlinkPool;
    }
  static connect(address: string, runner?: ContractRunner | null): MockUnlinkPool {
      return new Contract(address, _abi, runner) as unknown as MockUnlinkPool;
    }
  }

  
  