/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUnlinkPool, IUnlinkPoolInterface } from "../IUnlinkPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IUnlinkPool__factory {
    static readonly abi = _abi;
    static createInterface(): IUnlinkPoolInterface {
      return new Interface(_abi) as IUnlinkPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUnlinkPool {
      return new Contract(address, _abi, runner) as unknown as IUnlinkPool;
    }
  }
  